---
# Handler to handle DB tier notifications

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
    
- name: reaload ufw
  service:
    name: ufw
    state: reloaded
