---
# This playbook will install mysql and create db user and give permissions.

- name: install php on centos
  yum: 
    name: php
    state: latest
    when: ansible_os_family == "RedHat"  

- name: install mariadb server on centos
  yum: 
    name: mariadb-server
    state: present
    when: ansible_os_family == "RedHat"

- name: install php on centos
    apt:
      name: php
      state: latest
      when: ansible_os_family == "Debian"

- name: install mariadb server on centos
    apt:
      name: mariadb-server
      state: present
      when: ansible_os_family == "RedHat"


- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mariadb

- name: Start Mysql Service
  service:
    name: mariadb
    state: started
    enabled: yes
    notify: restart mariadb

- name: open firewall for mariadb in Redhat
  firewalld:
     service: mariadb
     zone: public
     permanent: true
     state: reloaded
 when: ansible_os_family == "RedHat"
 notify: "reload firewalld"

- name: open firewall for mariadb in Redhat
    firewalld:
       service: mariadb
       zone: public
       permanent: true
       state: reloaded
       when: ansible_os_family == "Debian"
       notify: "reload ufw"


- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: '%'
    state: present
